name: snowplow_flutter_tracker
description: Snowplow event tracker for Flutter. Add analytics to your Flutter apps and games http:&#x2F;&#x2F;snowplowanalytics.com
version: 0.0.1
author: Patrik Szabó <patricktailor@icloud.com>
homepage: https://github.com/patricktailor/snowplow-flutter-tracker

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  built_collection: 4.3.2
  built_value: 7.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: 1.10.0
  built_value_generator: 7.1.0
  pedantic: 1.9.0

flutter:
  plugin:
    androidPackage: com.patricktailor.snowplow_flutter_tracker
    pluginClass: SnowplowFlutterTrackerPlugin